spring.application.name=nezai
server.port=8081
ollama.url=http://localhost:11434
ollama.model=qwen3.5:4b
ollama.think=false
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB